server:
  port: 8090
app:
  brokerUrl: "tcp://localhost:61616"
  userName: "admin"
  password: "admin"
  tjmQueue: "jms-tjm"
  messageType: "TEXT"

brokilone:
  jms:
    queue: "brokilone.jms.queue"
    queueObject: "brokilone.jms.queue.object"